module.exports = {
  port: 3000,
  events: [
    "Admeta",
    "Fortuna",
    "Inventio",
    "Gratia",
    "Panache",
    "Football",
    "Basketball",
    "Tug of War",
    "E-sports",
    "Carmen",
    "Mr. and Mrs. Perseverantia",
    "Explorare",
    "Fabula",
    "Artem",
    "Sociale",
  ],
  schools: [
    "Vissanji Academy",
    "Childrens Academy International Malad",
    "Childrens Academy Malad",
    "CNM School",
    "Pawar Public Chandivali",
    "Bombay Scottish, Powai",
    "NSM School",
    "Euro School, Airoli",
    "Gundecha Academy",
    "HFS Thane",
    "Children's Academy Kandivali",
    "AVM, Bandra (W)",
    "Gokuldham High School",
    "Christ Church",
    "Lakshdham High School",
    "Jasudben ML",
    "Akshara High School",
    "Shishuvan School",
    "St. Peters",
    "Pawar Public School, Kandivali",
    "Pawar Public School, Bhandup",
    "VIBGYOR High, Goregaon",
    "St. Gregorious High School",
    "Utpal Sanghvi",
    "Thakur Public School",
    "JB Vaccha",
    "Sanjeevani",
    "RBK Mira Road",
    "Next School",
    "HFS Powai"
  ]
};
